services:
  - type: web
    name: shl-assessment-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
