services: 
  - type: web
    name: shl-assessment-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    region: oregon
    plan: free
    branch: main
    autoDeploy: true
